/**/robotnik_pad:
  ros__parameters:
    desired_freq: 30.0
    pad:
      num_of_buttons: 11 # When using a gamepad Logitech F710 in mode X
      num_of_axes: 8 # When using a gamepad Logitech F710 in mode X
      joy_topic: joy
      joy_timeout: 1.0
    plugins:
      - Movement

    Movement:
      type: robotnik_pad_plugins/Movement
      max_linear_speed: 1.0
      max_angular_speed: 1.5
      cmd_topic_vel: twist_cmd/joypad
      config:
        button_deadman: 5
        axis_linear_x: 1
        axis_linear_y: 0
        axis_angular_z: 3
        button_speed_up: 3
        button_speed_down: 0
        button_kinematic_mode: 2
        use_accel_watchdog: False
        axis_watchdog: [6,7,8]
        watchdog_duration: 0.0
